//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsHub.API.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SportsHub.API.Resources.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sys.Application.add_load(editNode); function editNode(){ var tree = $find(\&apos;{0}&apos;);var node = tree.findNodeByValue(&apos;{1}&apos;);if (node) node.startEdit();Sys.Application.remove_load(editNode);};.
        /// </summary>
        public static string AddNodeJS {
            get {
                return ResourceManager.GetString("AddNodeJS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Subscription.
        /// </summary>
        public static string ConfigureSubscription {
            get {
                return ResourceManager.GetString("ConfigureSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;object classid=&apos;clsid:D27CDB6E-AE6D-11cf-96B8-444553540000&apos; codebase=&apos;http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=7,0,19,0&apos;width=&apos;200px&apos; height=&apos;265px&apos;&gt;&lt;param name=&apos;movie&apos; value=&apos;Thumb_rotator.swf&apos; /&gt;&lt;embed src=&apos;Thumb_rotator.swf&apos; id=&apos;swf_std&apos; quality=&apos;high&apos; pluginspage=&apos;http://www.macromedia.com/go/getflashplayer&apos;type=&apos;application/x-shockwave-flash&apos; width=&apos;200px&apos; height=&apos;265px&apos;&gt;&lt;/embed&gt;&lt;/object&gt;.
        /// </summary>
        public static string FlashHTML {
            get {
                return ResourceManager.GetString("FlashHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Parent, We received {0} on {1} for term {2}, Thanks -Samvaad..
        /// </summary>
        public static string paymentReceive {
            get {
                return ResourceManager.GetString("paymentReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Parent, REMINDER-Fees upto {0} &amp; dues if any,must be paid on or before{1}.Ignore if paid already -Samvaad..
        /// </summary>
        public static string paymentReminder {
            get {
                return ResourceManager.GetString("paymentReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increased level of the male hormone androgen testosterone and estrogen deficiency are both suggestive of PCOS. This should show up in a blood test..
        /// </summary>
        public static string SMSTemplate {
            get {
                return ResourceManager.GetString("SMSTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member.
        /// </summary>
        public static string Student {
            get {
                return ResourceManager.GetString("Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _blank.
        /// </summary>
        public static string TargetConfigureSubscription {
            get {
                return ResourceManager.GetString("TargetConfigureSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainer.
        /// </summary>
        public static string Trainer {
            get {
                return ResourceManager.GetString("Trainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0}, Thank you for Registering OUK. Please use below credentials to login URL : {1}  Username : {2}  password : {3}  Thanks..
        /// </summary>
        public static string usernotification {
            get {
                return ResourceManager.GetString("usernotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify your newly added email address.
        /// </summary>
        public static string Verifyemail {
            get {
                return ResourceManager.GetString("Verifyemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome Guest.
        /// </summary>
        public static string WelcomeGuest {
            get {
                return ResourceManager.GetString("WelcomeGuest", resourceCulture);
            }
        }
    }
}
