//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsHub.API.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataDictionary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataDictionary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SportsHub.API.Resources.DataDictionary", typeof(DataDictionary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bdbca9a7.
        /// </summary>
        public static string Acadamic_Year {
            get {
                return ResourceManager.GetString("Acadamic Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a2e00299.
        /// </summary>
        public static string AddressType {
            get {
                return ResourceManager.GetString("AddressType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4ba80130.
        /// </summary>
        public static string ApproveBlogNotification {
            get {
                return ResourceManager.GetString("ApproveBlogNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5bacc3e4.
        /// </summary>
        public static string ApproveGroupNotfiecation {
            get {
                return ResourceManager.GetString("ApproveGroupNotfiecation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 84f10760.
        /// </summary>
        public static string CBT {
            get {
                return ResourceManager.GetString("CBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4a74376a.
        /// </summary>
        public static string Certification {
            get {
                return ResourceManager.GetString("Certification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d5040bff.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 28866c50.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 024f7150.
        /// </summary>
        public static string ContentType {
            get {
                return ResourceManager.GetString("ContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ab0b614c.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16d390dc.
        /// </summary>
        public static string Course {
            get {
                return ResourceManager.GetString("Course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a99f0edc.
        /// </summary>
        public static string Course_Year {
            get {
                return ResourceManager.GetString("Course Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ab1585b3.
        /// </summary>
        public static string CourseAssignment {
            get {
                return ResourceManager.GetString("CourseAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to b795a10d.
        /// </summary>
        public static string CoursePayments {
            get {
                return ResourceManager.GetString("CoursePayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4ced13e4.
        /// </summary>
        public static string Courseware {
            get {
                return ResourceManager.GetString("Courseware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to b2cf1690.
        /// </summary>
        public static string CustomUrlNotification {
            get {
                return ResourceManager.GetString("CustomUrlNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d61f9eca.
        /// </summary>
        public static string Demonstration_Type {
            get {
                return ResourceManager.GetString("Demonstration_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 428f97c6.
        /// </summary>
        public static string District {
            get {
                return ResourceManager.GetString("District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 84f10760.
        /// </summary>
        public static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d5a152b3.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3a4338ae.
        /// </summary>
        public static string EmployementStatus {
            get {
                return ResourceManager.GetString("EmployementStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 46652623.
        /// </summary>
        public static string EmployementType {
            get {
                return ResourceManager.GetString("EmployementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cc3eb25f.
        /// </summary>
        public static string EventType {
            get {
                return ResourceManager.GetString("EventType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aad60388.
        /// </summary>
        public static string FAQs {
            get {
                return ResourceManager.GetString("FAQs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2fa1c39e.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6cb13da6.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48acc59f.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8b3b221a.
        /// </summary>
        public static string LogType {
            get {
                return ResourceManager.GetString("LogType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to b1b5c0e5.
        /// </summary>
        public static string MaritalStatus {
            get {
                return ResourceManager.GetString("MaritalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3a7872f9.
        /// </summary>
        public static string Member {
            get {
                return ResourceManager.GetString("Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 39080bf1.
        /// </summary>
        public static string MultiAnswer {
            get {
                return ResourceManager.GetString("MultiAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd57541d.
        /// </summary>
        public static string MultiChoice {
            get {
                return ResourceManager.GetString("MultiChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1632fb7f.
        /// </summary>
        public static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1632fb7f.
        /// </summary>
        public static string OnlineMaterial {
            get {
                return ResourceManager.GetString("OnlineMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to daa8956f.
        /// </summary>
        public static string Organization {
            get {
                return ResourceManager.GetString("Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1ac8a2c6.
        /// </summary>
        public static string Percentage {
            get {
                return ResourceManager.GetString("Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a02a5d0d.
        /// </summary>
        public static string Poll {
            get {
                return ResourceManager.GetString("Poll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 86f3344d.
        /// </summary>
        public static string PostAssessment {
            get {
                return ResourceManager.GetString("PostAssessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2524aa00.
        /// </summary>
        public static string PostAssessmentNotification {
            get {
                return ResourceManager.GetString("PostAssessmentNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0701774e.
        /// </summary>
        public static string PreAssessment {
            get {
                return ResourceManager.GetString("PreAssessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fb332dc3.
        /// </summary>
        public static string Priviliges {
            get {
                return ResourceManager.GetString("Priviliges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c8a33817.
        /// </summary>
        public static string ProficiencyLevel {
            get {
                return ResourceManager.GetString("ProficiencyLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 521a408c.
        /// </summary>
        public static string ProjectLocation {
            get {
                return ResourceManager.GetString("ProjectLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8594a646.
        /// </summary>
        public static string ProjectLocationType {
            get {
                return ResourceManager.GetString("ProjectLocationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e2dd28ef.
        /// </summary>
        public static string RegisterationNotification {
            get {
                return ResourceManager.GetString("RegisterationNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a2c992da.
        /// </summary>
        public static string Sections {
            get {
                return ResourceManager.GetString("Sections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to b118864f.
        /// </summary>
        public static string Semester {
            get {
                return ResourceManager.GetString("Semester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e71158bc.
        /// </summary>
        public static string Sms {
            get {
                return ResourceManager.GetString("Sms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8770eec8.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3791650a.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 02e1d48e.
        /// </summary>
        public static string SubscriptionNotification {
            get {
                return ResourceManager.GetString("SubscriptionNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4d3316f3.
        /// </summary>
        public static string Survey {
            get {
                return ResourceManager.GetString("Survey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6b3e15ca.
        /// </summary>
        public static string TaskType {
            get {
                return ResourceManager.GetString("TaskType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 797537f0.
        /// </summary>
        public static string TextAnswer {
            get {
                return ResourceManager.GetString("TextAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8f3db27e.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8a03f1c4.
        /// </summary>
        public static string UserType {
            get {
                return ResourceManager.GetString("UserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to b918e5c8.
        /// </summary>
        public static string VideoConference {
            get {
                return ResourceManager.GetString("VideoConference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6ec3a5ba.
        /// </summary>
        public static string Videos {
            get {
                return ResourceManager.GetString("Videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fbd5afa6.
        /// </summary>
        public static string YesNo {
            get {
                return ResourceManager.GetString("YesNo", resourceCulture);
            }
        }
    }
}
