//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsHub.API.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmailMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SportsHub.API.Resources.EmailMessage", typeof(EmailMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessment for Validation.
        /// </summary>
        public static string Accessorvalidationsubject {
            get {
                return ResourceManager.GetString("Accessorvalidationsubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessment Schedule.
        /// </summary>
        public static string AssessmentMail {
            get {
                return ResourceManager.GetString("AssessmentMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table style=&quot;width: 100%;border: 1px solid #C3C3C5;border-radius: 10px;&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///&lt;tbody&gt;
        ///&lt;tr&gt;&lt;td style=&quot;width: 100%; padding-left: 20px; padding-right: 20px&quot;&gt;&lt;br&gt;Dear User,&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;&lt;td style=&quot;width: 100%; padding-left: 20px; padding-right: 20px&quot;&gt;&lt;br&gt;{0},{1} have been scheduled for the course {2} &lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;&lt;td style=&quot;width: 100%; padding-left: 20px; padding-right: 20px&quot;&gt;Please find the course details below:&lt;/td&gt;&lt;/tr&gt;
        /// &lt;tr&gt;&lt;td style=&quot;width: 100%; padding-left: 20px; p [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AssessmentMessage {
            get {
                return ResourceManager.GetString("AssessmentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessment Result.
        /// </summary>
        public static string AssessmentResult {
            get {
                return ResourceManager.GetString("AssessmentResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table style=&quot;width: 100%;border: 1px solid #C3C3C5;border-radius: 10px;&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///&lt;tbody&gt;&lt;tr&gt;&lt;td style=&quot;width: 100%;background-color: #C3C3C5;height: 60px;color: #45748F;font-size: large;border-top-left-radius: 10px;border-top-right-radius: 10px;&quot;&gt;&amp;nbsp; &amp;nbsp; &amp;nbsp;{0}&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;&lt;td style=&quot;width: 100%; padding-left: 20px; padding-right: 20px&quot;&gt;&lt;br&gt;Dear {1},&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;&lt;td style=&quot;width: 100%; padding-left: 20px; padding-right: 20px&quot;&gt;&lt;br&gt;{2}You have completed your Assessmen [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AssessmentResultStudent {
            get {
                return ResourceManager.GetString("AssessmentResultStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table style=&quot;width: 100%;border: 1px solid #C3C3C5;border-radius: 10px;&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///&lt;tbody&gt;&lt;tr&gt;&lt;td style=&quot;width: 100%;background-color: #C3C3C5;height: 60px;color: #45748F;font-size: large;border-top-left-radius: 10px;border-top-right-radius: 10px;&quot;&gt;&amp;nbsp; &amp;nbsp; &amp;nbsp;{0}&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;&lt;td style=&quot;width: 100%; padding-left: 20px; padding-right: 20px&quot;&gt;&lt;br&gt;Dear User,&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;&lt;td style=&quot;width: 100%; padding-left: 20px; padding-right: 20px&quot;&gt;&lt;br&gt;{1},{2} have been scheduled for the [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AssessmentScheduleOutlook {
            get {
                return ResourceManager.GetString("AssessmentScheduleOutlook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table style=&quot;width: 100%;border: 1px solid #C3C3C5;border-radius: 10px;&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///&lt;tbody&gt;&lt;tr&gt;&lt;td style=&quot;width: 100%;background-color: #C3C3C5;height: 60px;color: #45748F;font-size: large;border-top-left-radius: 10px;border-top-right-radius: 10px;&quot;&gt;&amp;nbsp; &amp;nbsp; &amp;nbsp;{0}&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;&lt;td style=&quot;width: 100%; padding-left: 20px; padding-right: 20px&quot;&gt;&lt;br&gt;Dear {1},&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td style=&quot;width: 100%; padding-left: 20px; padding-right: 20px&quot;&gt;&lt;br&gt;Your assessment has been validated by  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AssessmentValidated {
            get {
                return ResourceManager.GetString("AssessmentValidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned to new course.
        /// </summary>
        public static string AssignTrainer {
            get {
                return ResourceManager.GetString("AssignTrainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Dear Trainer&lt;br&gt;&lt;br&gt;
        ///
        ///You have assigned to the new course &lt;br&gt;&lt;br&gt;
        ///
        ///Thanks and Regards,&lt;br&gt;
        ///{0}.&lt;/p&gt;.
        /// </summary>
        public static string AssignTrainerDetails {
            get {
                return ResourceManager.GetString("AssignTrainerDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Dear User&lt;br&gt;&lt;br&gt;
        ///
        ///Your No. of Attempts left is Zero.Please Contact Administrator &lt;br&gt;&lt;br&gt;
        ///
        ///Thanks and Regards,&lt;br&gt;
        ///{0}.&lt;/p&gt;.
        /// </summary>
        public static string AttemptsDetails {
            get {
                return ResourceManager.GetString("AttemptsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. of Attempts finished.
        /// </summary>
        public static string AttemptsSub {
            get {
                return ResourceManager.GetString("AttemptsSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table style=&quot;width: 100%;border: 1px solid #C3C3C5;border-radius: 10px;&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///&lt;tbody&gt;
        ///&lt;tr&gt;&lt;td style=&quot;width: 100%; padding-left: 20px; padding-right: 20px&quot;&gt;&lt;br&gt;Dear User,&lt;br&gt;&lt;br&gt;&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;
        ///&lt;td style=&quot;width: 100%; padding-left: 20px; padding-right: 20px&quot;&gt;Your Blog is Declined&lt;br&gt;&lt;br&gt;
        ///&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;tr&gt;&lt;td style=&quot;width: 100%; padding-left: 20px; padding-right: 20px&quot;&gt;&lt;br&gt;Thanks and Regards,&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;&lt;td style=&quot;width: 100%; padding-left: 20px; padding-right: 20px&quot;&gt;&lt;b&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Blogdecline {
            get {
                return ResourceManager.GetString("Blogdecline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog Declined.
        /// </summary>
        public static string blogdeclinesubject {
            get {
                return ResourceManager.GetString("blogdeclinesubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br /&gt;&lt;table style=&apos;width: 100%&apos; cellpadding=&apos;0&apos; cellspacing=&apos;0&apos;&gt;
        ///        &lt;tr&gt;&lt;td style=&apos;width: 10%&apos;&gt;&lt;/td&gt;&lt;td style=&apos;width: 80%&apos;&gt;
        ///        &lt;table style=&apos;width: 100%;border: 1px solid #C3C3C5;border-radius: 10px;&apos; cellpadding=&apos;0&apos; cellspacing=&apos;0&apos;&gt;
        ///       &lt;tr&gt;&lt;td style=&apos;width: 100%;background-color: #C3C3C5;height: 60px;color: #45748F;font-size: large;border-top-left-radius: 10px;border-top-right-radius: 10px;&apos;&gt;&amp;nbsp; &amp;nbsp; &amp;nbsp;Password Recovery&lt;/td&gt;&lt;/tr&gt;
        ///        &lt;tr&gt;&lt;td style=&apos;width: 100%; padding-left: [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table style=&quot;width: 100%&quot;&gt;&lt;tbody&gt;&lt;tr&gt;&lt;td style=&quot;width: 5%&quot;&gt;&lt;/td&gt;&lt;td style=&quot;width: 70%&quot;&gt;&lt;br&gt;&lt;table style=&quot;width: 100%&quot;&gt;&lt;tbody&gt;&lt;tr&gt;&lt;td style=&quot;width: 5%&quot;&gt;&lt;/td&gt;&lt;td style=&quot;width: 70%&quot;&gt;&lt;table style=&quot;width: 100%;border: 1px solid #C3C3C5;border-radius: 10px;&quot;&gt;&lt;tbody&gt;&lt;tr&gt;&lt;td align=&quot;center&quot; style=&quot;width: 100%;background-color: #C3C3C5;height: 60px;color: #45748F;font-size: large;border-top-left-radius: 10px;border-top-right-radius: 10px;&quot;&gt;Contact Us&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td align=&quot;center&quot;&gt;&lt;br&gt;&lt;span style=&quot;font-size:medium; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br /&gt;&lt;table style=&apos;width: 100%&apos;&gt;&lt;tr&gt;&lt;td style=&apos;width: 5%&apos;&gt;&lt;/td&gt;&lt;td style=&apos;width: 70%&apos;&gt;&lt;table style=&apos;width: 100%;border: 1px solid #C3C3C5;border-radius: 10px;&apos;&gt;&lt;tr&gt;&lt;td align=&apos;center&apos; style=&apos;width: 100%;background-color: #C3C3C5;height: 60px;color: #45748F;font-size: large;border-top-left-radius: 10px;border-top-right-radius: 10px;&apos;&gt;Contact Us&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;&lt;br /&gt;Dear {0},&lt;br /&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;Details of the User mentioned below.&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;&lt;br/&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;&lt;table style=&apos;padding-left: 20px; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ContactUSExternal {
            get {
                return ResourceManager.GetString("ContactUSExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table style=&quot;width: 100%&quot;&gt;&lt;tbody&gt;&lt;tr&gt;&lt;td style=&quot;width: 5%&quot;&gt;&lt;/td&gt;&lt;td style=&quot;width: 70%&quot;&gt;&lt;br&gt;&lt;table style=&quot;width: 100%&quot;&gt;&lt;tbody&gt;&lt;tr&gt;&lt;td style=&quot;width: 5%&quot;&gt;&lt;/td&gt;&lt;td style=&quot;width: 70%&quot;&gt;&lt;table style=&quot;width: 100%;border: 1px solid #C3C3C5;border-radius: 10px;&quot;&gt;&lt;tbody&gt;&lt;tr&gt;&lt;td align=&quot;center&quot; style=&quot;width: 100%;background-color: #C3C3C5;height: 60px;color: #45748F;font-size: large;border-top-left-radius: 10px;border-top-right-radius: 10px;&quot;&gt;Contact Us&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td align=&quot;center&quot;&gt;&lt;br&gt;&lt;span style=&quot;font-size:medium; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ContactUsMail {
            get {
                return ResourceManager.GetString("ContactUsMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Admin,
        ///
        ///I would like to apply for a new course.
        ///
        ///Please find the details below.
        ///
        ///User Name : {0}
        ///Course Name : {1}
        ///Batch : {2}
        ///Start Date : {3}
        ///End Date : {4}
        ///Course Apply Date : {5}
        ///Learning Mode : {6}
        ///
        ///Thanks and Regards,
        ///{7}.
        /// </summary>
        public static string CourseApply {
            get {
                return ResourceManager.GetString("CourseApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;&lt;body&gt;&lt;Table style=&apos;font-family:Arial;font-size:9pt&apos;&gt;&lt;tr&gt;&lt;td style=&apos;font-family: Arial&apos;&gt;Dear {0},&lt;br/&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;&lt;br/&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;&lt;br/&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td style=&apos;font-family: Arial&apos;&gt;Congratulations!!!&lt;br&gt;&lt;br/&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td style=&apos;font-family: Verdana&apos;&gt;You have completed the course assigned to you.&lt;br&gt;&lt;br/&gt;&lt;/tr&gt;&lt;/td&gt;&lt;tr&gt;&lt;td&gt;&lt;br/&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;&lt;br/&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td style=&apos;font-family: Verdana&apos;&gt;Thanks and Regards&lt;/td&gt;&lt;/tr&gt; &lt;tr&gt;&lt;td style=&apos;font-family: Verdana&apos;&gt;{1}&lt;/td&gt;&lt;/tr&gt;&lt;tr [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CourseComplete {
            get {
                return ResourceManager.GetString("CourseComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LMS Course Completion Details.
        /// </summary>
        public static string CourseCompletionDetails {
            get {
                return ResourceManager.GetString("CourseCompletionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table style=&quot;width: 100%;border: 1px solid #C3C3C5;border-radius: 10px;&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///&lt;tbody&gt;
        ///&lt;tr&gt;&lt;td style=&quot;width: 100%; padding-left: 20px; padding-right: 20px&quot;&gt;&lt;br&gt;Dear {0} {1},&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;&lt;td style=&quot;width: 100%; padding-left: 20px; padding-right: 20px&quot;&gt;&lt;br&gt;You have been successfully enrolled to the course &lt;b&gt;{2}&lt;b&gt;. &lt;/b&gt;&lt;/b&gt;&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;&lt;td style=&quot;width: 100%; padding-left: 20px; padding-right: 20px&quot;&gt;Please find the course details below:&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;&lt;td style=&quot;width: 100 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CourseEnrollementNotification {
            get {
                return ResourceManager.GetString("CourseEnrollementNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Enrollment Confirmation.
        /// </summary>
        public static string CourseEnrollmentconfirmationSubject {
            get {
                return ResourceManager.GetString("CourseEnrollmentconfirmationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table style=&quot;width: 100%;border: 1px solid #C3C3C5;border-radius: 10px;&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///&lt;tbody&gt;
        ///&lt;tr&gt;&lt;td style=&quot;width: 100%; padding-left: 20px; padding-right: 20px&quot;&gt;&lt;br&gt;Dear Admin,&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;&lt;td style=&quot;width: 100%; padding-left: 20px; padding-right: 20px&quot;&gt;&lt;br&gt;The following user has successfully enrolled to the course {0}. &lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;&lt;td style=&quot;width: 100%; padding-left: 20px; padding-right: 20px&quot;&gt;Please find the course details below:&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;&lt;td style=&quot;width: 100%&quot;&gt;&lt;br&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Courseenrollmentdetailstoadmin {
            get {
                return ResourceManager.GetString("Courseenrollmentdetailstoadmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Enrollment Details.
        /// </summary>
        public static string Courseenrollmentdetailstoadminsubjest {
            get {
                return ResourceManager.GetString("Courseenrollmentdetailstoadminsubjest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table style=&quot;width: 100%;border: 1px solid #C3C3C5;border-radius: 10px;&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///&lt;tbody&gt;&lt;tr&gt;&lt;td style=&quot;width: 100%;background-color: #C3C3C5;height: 60px;color: #45748F;font-size: large;border-top-left-radius: 10px;border-top-right-radius: 10px;&quot;&gt;&amp;nbsp; &amp;nbsp; &amp;nbsp;Course Enrollment Confirmation&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;&lt;td style=&quot;width: 100%; padding-left: 20px; padding-right: 20px&quot;&gt;&lt;br&gt;Dear {0}  {1},&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;&lt;td style=&quot;width: 100%; padding-left: 20px; padding-right: 20px&quot;&gt;&lt;br&gt;You  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CourseEnrolmentNotification {
            get {
                return ResourceManager.GetString("CourseEnrolmentNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0}, 
        ///
        ///Welcome to {1} ! 
        ///{2}
        ///Please note that the course duration is {3} days.
        ///
        ///You would need to necessarily take the pre assessment test before starting the course.For any assistance, please use the Help Desk on the portal.
        ///
        ///Wish you all the best!
        ///
        ///Thanks and Regards,
        ///{4}..
        /// </summary>
        public static string CourseSchedule {
            get {
                return ResourceManager.GetString("CourseSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table style=&quot;width: 100%&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///&lt;tbody&gt;&lt;tr&gt;&lt;td style=&quot;width: 10%&quot;&gt;&lt;/td&gt;&lt;td style=&quot;width: 80%&quot;&gt;
        ///&lt;table style=&quot;width: 100%;border: 1px solid #C3C3C5;border-radius: 10px;&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///&lt;tbody&gt;&lt;tr&gt;&lt;td style=&quot;width: 100%; background-color: rgb(195, 195, 197); height: 60px; color: rgb(69, 116, 143); font-size: large; border-top-left-radius: 10px; border-top-right-radius: 10px; padding-left: 40px;&quot;&gt;{0}&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;&lt;td style=&quot;width: 100%; padding-left: 20px; pad [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CourseScheduleNoteftoTrainer {
            get {
                return ResourceManager.GetString("CourseScheduleNoteftoTrainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Course.
        /// </summary>
        public static string CourseScheduleNoteftoTrainerSub {
            get {
                return ResourceManager.GetString("CourseScheduleNoteftoTrainerSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;&lt;body&gt;&lt;table style=&apos;font-family:arial;font-size:9pt&apos;&gt;&lt;tr&gt;&lt;td style=&apos;font-family: arial&apos;&gt; Dear {0}, &lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td style=&apos;font-family: arial&apos;&gt;Welcome to {1} !&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;{2}&lt;br/&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td style=&apos;font-family: arial&apos;&gt;Please note that the course duration is {3} days&lt;br/&gt;&lt;br/&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td style=&apos;font-family: arial&apos;&gt;You would need to necessarily take the pre assessment test before starting the course.For any assistance, please use the Help Desk on the portal.&lt;br/&gt;&lt;br/&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CourseScheduleOutlook {
            get {
                return ResourceManager.GetString("CourseScheduleOutlook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Fellow users registered for the same course are 
        ///
        ///{0}
        ///.
        /// </summary>
        public static string CourseScheduleSub {
            get {
                return ResourceManager.GetString("CourseScheduleSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;&lt;td style=&apos;font-family: arial&apos;&gt;Fellow users registered for the same course are &lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;{0}&lt;/td&gt;&lt;/tr&gt;.
        /// </summary>
        public static string CourseScheduleSubOutlook {
            get {
                return ResourceManager.GetString("CourseScheduleSubOutlook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br /&gt;&lt;table style=&apos;width: 100%&apos; cellpadding=&apos;0&apos; cellspacing=&apos;0&apos;&gt;
        ///&lt;tr&gt;&lt;td style=&apos;width: 10%&apos;&gt;&lt;/td&gt;&lt;td style=&apos;width: 80%&apos;&gt;
        ///&lt;table style=&apos;width: 100%;border: 1px solid #C3C3C5;border-radius: 10px;&apos; 
        ///
        ///cellpadding=&apos;0&apos; cellspacing=&apos;0&apos;&gt;
        ///&lt;tr&gt;&lt;td style=&apos;width: 100%;background-color: #C3C3C5;height: 60px;color: 
        ///
        ///#45748F;font-size: large;border-top-left-radius: 10px;border-top-right-radius: 
        ///
        ///10px;&apos;&gt;&amp;nbsp; &amp;nbsp; &amp;nbsp;Registration URL&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;&lt;td style=&apos;width: 100%; padding-left: 20px; padding-right [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CustomURLEmail {
            get {
                return ResourceManager.GetString("CustomURLEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table style=&quot;width: 100%;border: 1px solid #C3C3C5;border-radius: 10px;&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///       &lt;tbody&gt;&lt;tr&gt;&lt;td style=&quot;width: 100%;background-color: #C3C3C5;height: 60px;color: #45748F;font-size: large;border-top-left-radius: 10px;border-top-right-radius: 10px;&quot;&gt;&amp;nbsp; &amp;nbsp; &amp;nbsp;New Primary Email address&lt;/td&gt;&lt;/tr&gt;
        ///        &lt;tr&gt;&lt;td style=&quot;width: 100%; padding-left: 20px; padding-right: 20px&quot;&gt;&lt;br&gt;&lt;br&gt;Dear {0} {1},&lt;br&gt;&lt;br&gt;&lt;/td&gt;&lt;/tr&gt;
        ///        &lt;tr&gt;&lt;td style=&quot;width: 100%; padding-left: 20px;  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EmailChange {
            get {
                return ResourceManager.GetString("EmailChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Sir/Madam,
        ///&lt;br&gt;
        ///&lt;br&gt;
        ///Thank you for registering with us, you are eligible for a 20% discount on our whole ERP package. For more details on your pricing, our sales team will contact you within 24 working hours.
        ///&lt;br&gt;
        ///&lt;br&gt;
        ///Regards,
        ///Samvaad ERP Team..
        /// </summary>
        public static string EnquiryRegister {
            get {
                return ResourceManager.GetString("EnquiryRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EventRequestPopUp {
            get {
                return ResourceManager.GetString("EventRequestPopUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum Approval Request.
        /// </summary>
        public static string ForamApprovalRequest {
            get {
                return ResourceManager.GetString("ForamApprovalRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table style=&quot;width: 100%;border: 1px solid #C3C3C5;border-radius: 10px;&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///&lt;tbody&gt;
        ///&lt;tr&gt;&lt;td style=&quot;width: 100%; padding-left: 20px; padding-right: 20px&quot;&gt;&lt;br&gt;Dear Admin,&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;&lt;td style=&quot;width: 100%; padding-left: 20px; padding-right: 20px&quot;&gt;&lt;br&gt;A new forum has been created under the course ({0}) &lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;&lt;td style=&quot;width: 100%; padding-left: 20px; padding-right: 20px&quot;&gt;Please kindly review and approve it.&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;&lt;td style=&quot;width: 100%; padding-left: 20p [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ForamTopicApprovalRequest {
            get {
                return ResourceManager.GetString("ForamTopicApprovalRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table style=&quot;width: 100%&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///        &lt;tbody&gt;&lt;tr&gt;&lt;td style=&quot;width: 10%&quot;&gt;&lt;/td&gt;&lt;td style=&quot;width: 80%&quot;&gt;
        ///        &lt;table style=&quot;width: 100%;border: 1px solid #C3C3C5;border-radius: 10px;&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///       &lt;tbody&gt;&lt;tr&gt;&lt;td style=&quot;width: 100%;background-color: #C3C3C5;height: 60px;color: #45748F;font-size: large;border-top-left-radius: 10px;border-top-right-radius: 10px;&quot;&gt;&amp;nbsp; &amp;nbsp; &amp;nbsp;Password Recovery&lt;/td&gt;&lt;/tr&gt;
        ///        &lt;tr&gt;&lt;td style=&quot;width: 100%; paddi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ForgetPassword {
            get {
                return ResourceManager.GetString("ForgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new thread has been Approved.
        /// </summary>
        public static string ForumThreadApproved {
            get {
                return ResourceManager.GetString("ForumThreadApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new thread has been Rejected.
        /// </summary>
        public static string ForumThreadRejected {
            get {
                return ResourceManager.GetString("ForumThreadRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table style=&apos;font-family:Arial;font-size:9pt&apos;&gt;&lt;tr&gt;&lt;td&gt; Dear {0},&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td width=&apos;600px&apos;&gt;Your new thread has been {1} by admin&lt;table style=&apos;width: 600px&apos;&gt;&lt;tr&gt;&lt;td class=&apos;style2&apos; colspan=&apos;3&apos;&gt;&lt;b&gt;Details&lt;/b&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td style=&apos;width: 35%&apos;&gt;Thread Name&lt;/td&gt;&lt;td style=&apos;width: 2%&apos;&gt;&lt;b&gt;:&lt;/b&gt;&lt;/td&gt;&lt;td style=&apos;width: 63%&apos;&gt;       {2}&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt; Thanks and Regards &lt;br/&gt;{3}&lt;br/&gt;&lt;br/&gt;Any Queries, Contact Admin&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt; Note. This is an automated email. Kindly do not reply to this [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ForumTopic {
            get {
                return ResourceManager.GetString("ForumTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Dear Admin,&lt;br&gt;&lt;br&gt;
        ///
        ///Please Approve my request for joining group below are the details.&lt;br&gt;&lt;br&gt;
        ///
        ///User name: {0}&lt;br&gt;
        ///Group name: {1}&lt;br&gt;
        ///Login name: {2}&lt;br&gt;&lt;br&gt;
        ///
        ///Need Your Approval.&lt;br&gt;&lt;br&gt;
        ///
        ///  Thanks and Regards,&lt;br&gt;{3}.&lt;br&gt;&lt;/p&gt;.
        /// </summary>
        public static string GroupApprovalRequest {
            get {
                return ResourceManager.GetString("GroupApprovalRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Dear User,&lt;br&gt;&lt;br&gt;
        ///
        ///You have been successfully added to group: {0} &lt;br&gt;&lt;br&gt;
        ///
        ///Approved By: {1}&lt;br&gt;&lt;br&gt;
        ///
        ///Thanks and Regards,&lt;br&gt;
        ///{2}.&lt;/p&gt;.
        /// </summary>
        public static string GroupApproved {
            get {
                return ResourceManager.GetString("GroupApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table style=&quot;width: 100%;border: 1px solid #C3C3C5;border-radius: 10px;&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///&lt;tbody&gt;&lt;tr&gt;&lt;td style=&quot;width: 100%;background-color: #C3C3C5;height: 60px;color: #45748F;font-size: large;border-top-left-radius: 10px;border-top-right-radius: 10px;&quot;&gt;&amp;nbsp; &amp;nbsp; &amp;nbsp;{0}&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;&lt;td style=&quot;width: 100%; padding-left: 20px; padding-right: 20px&quot;&gt;&lt;br&gt;Dear User,&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;&lt;td style=&quot;width: 100%; padding-left: 20px; padding-right: 20px&quot;&gt;&lt;br&gt;New folder has been shared for the  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GroupMail {
            get {
                return ResourceManager.GetString("GroupMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Dear User,&lt;br&gt;&lt;br&gt;
        ///
        ///Your Request for joining the group has been rejected&lt;br&gt;&lt;br&gt;
        ///
        ///Rejected By : {0}&lt;br&gt;
        ///Group name: {1}&lt;br&gt;
        ///Reason for Rejection: {2}&lt;br&gt;&lt;br&gt;
        ///
        ///Thanks and Regards,&lt;br&gt;
        ///{3}.&lt;/p&gt;.
        /// </summary>
        public static string GroupRejected {
            get {
                return ResourceManager.GetString("GroupRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New folder added.
        /// </summary>
        public static string GroupSub {
            get {
                return ResourceManager.GetString("GroupSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table style=&apos;font-family: Arial; font-size: 9pt&apos;&gt;
        ///&lt;tr&gt;
        ///&lt;td style=&apos;font-family: Arial&apos;&gt;Dear&amp;nbsp;&amp;nbsp;{0},&lt;br /&gt;&lt;br /&gt;&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;
        ///&lt;td&gt;Your assessment has been send to assessor for validation, we will get back to you shortly.&lt;/td&gt;
        ///&lt;/tr&gt;&lt;/table&gt;&lt;table style=&apos;font-family: Arial; font-size: 9pt&apos;&gt;&lt;tr&gt;&lt;td style=&apos;font-family: Arial&apos;&gt;&lt;br /&gt;&lt;br /&gt;&amp;nbsp;Thanks &amp; Regards&lt;br /&gt;&amp;nbsp;{1}&lt;br /&gt;&lt;br /&gt;
        ///&amp;nbsp;Any Queries, Contact Admin&lt;br /&gt;&amp;nbsp;Note. This is an automated email. Kindly do not reply to this email [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IsSubjective {
            get {
                return ResourceManager.GetString("IsSubjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table style=&quot;width: 100%;border: 1px solid #C3C3C5;border-radius: 10px;&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///&lt;tbody&gt;&lt;tr&gt;&lt;td style=&quot;width: 100%;background-color: #C3C3C5;height: 60px;color: #45748F;font-size: large;border-top-left-radius: 10px;border-top-right-radius: 10px;&quot;&gt;&amp;nbsp; &amp;nbsp; &amp;nbsp;Confirence Details&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;&lt;td style=&quot;width: 100%; padding-left: 20px; padding-right: 20px&quot;&gt;&lt;br&gt;Dear User &lt;br&gt;&lt;br&gt;&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;
        ///&lt;td style=&quot;width: 100%; padding-left: 20px; padding-right: 20px&quot;&gt;Please Join Co [rest of string was truncated]&quot;;.
        /// </summary>
        public static string JoinConference {
            get {
                return ResourceManager.GetString("JoinConference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status of joining group.
        /// </summary>
        public static string JoiningGroup {
            get {
                return ResourceManager.GetString("JoiningGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your New Primary Email address.
        /// </summary>
        public static string NewPrimaryEmail {
            get {
                return ResourceManager.GetString("NewPrimaryEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Changed.
        /// </summary>
        public static string PasswordChanged {
            get {
                return ResourceManager.GetString("PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Recovery.
        /// </summary>
        public static string PasswordRecovery {
            get {
                return ResourceManager.GetString("PasswordRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt; Dear  &lt;b&gt;{0}&lt;/b&gt; &lt;br&gt; &lt;br&gt;        ///        ///Payment Successful!        /// &lt;br&gt;&lt;br&gt;You are now registered to the course -&lt;b&gt; {1}.&lt;/b&gt; &lt;/div&gt;&lt;br&gt;&lt;div&gt;Please find your login credentials below. &lt;/div&gt; &lt;br&gt;        ///&lt;b&gt;Login URL&lt;/b&gt;: {2}&lt;br&gt;        ///        ///&lt;b&gt;Username&lt;/b&gt; :        ///{3}&lt;br&gt;        ///&lt;b&gt;Password&lt;/b&gt; :{4}&lt;br&gt;&lt;br&gt;        ///        ///Regards,&lt;br&gt;        ///        ///Admin        ///  &lt;br&gt;&lt;div&gt;&lt;br&gt; &lt;b&gt;        ///NOTE:&lt;/b&gt;  Please change your password as soon as you login to your account. Also, this is system-generated email. Please do not respond..&lt;/div&gt;.
        /// </summary>
        public static string paymentConfirmation {
            get {
                return ResourceManager.GetString("paymentConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01//EN&quot; &quot;http://www.w3.org/TR/html4/strict.dtd&quot;&gt;
        ///&lt;html style=&quot;-moz-osx-font-smoothing: grayscale; -webkit-font-smoothing: antialiased; background-color: #464646; margin: 0; padding: 0;&quot;&gt;
        ///    &lt;head&gt;
        ///        &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;&gt;
        ///        &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///        &lt;meta name=&quot;format-detection&quot; content=&quot;telephone=no&quot;&gt;
        ///        &lt;title&gt;:: Shiksion Email&lt;/title&gt;
        ///                /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PaymentSuccess {
            get {
                return ResourceManager.GetString("PaymentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LMS Course Pre-Training Assessment Details.
        /// </summary>
        public static string PreAssessmentDetails {
            get {
                return ResourceManager.GetString("PreAssessmentDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privileges Information for Course.
        /// </summary>
        public static string PrivilegeInfoForCourse {
            get {
                return ResourceManager.GetString("PrivilegeInfoForCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table&gt;&lt;tr&gt;&lt;td&gt;Dear Admin,&lt;br/&gt;&lt;/br&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;Trainer {0}  has delegated their job to {1}   &lt;br&gt;&lt;br/&gt;&lt;/tr&gt;&lt;/td&gt;&lt;tr&gt;&lt;td&gt;&lt;b&gt;for the Course &lt;/b&gt; : {2} &lt;br/&gt;&lt;/br&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;&lt;b&gt;Start Date&lt;/b&gt; : {3} &lt;br/&gt;&lt;/br&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;&lt;b&gt;End Date&lt;/b&gt; : {4} &lt;br/&gt;&lt;/br&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;Thanks and Regards,&lt;/b&gt;&lt;/b&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;{5}.&lt;/b&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;&lt;br/&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;.
        /// </summary>
        public static string PrivilegesAdmin {
            get {
                return ResourceManager.GetString("PrivilegesAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;&lt;body&gt;&lt;Table&gt;&lt;tr&gt;&lt;td&gt;Dear User,&lt;br/&gt;&lt;/br&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;Your Privileges Information for Course has sent to Admin &lt;br&gt;&lt;br/&gt;&lt;/tr&gt;&lt;/td&gt;&lt;tr&gt;&lt;td&gt;Thanks and Regards,&lt;/b&gt;&lt;/b&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;{0}.&lt;/b&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;&lt;br/&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;/body&gt;&lt;/html&gt;.
        /// </summary>
        public static string PrivilegesUser {
            get {
                return ResourceManager.GetString("PrivilegesUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table style=&quot;width: 100%;border: 1px solid #C3C3C5;border-radius: 10px;&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///&lt;tbody&gt;&lt;tr&gt;&lt;td style=&quot;width: 100%;background-color: #C3C3C5;height: 60px;color: #45748F;font-size: large;border-top-left-radius: 10px;border-top-right-radius: 10px;&quot;&gt;&amp;nbsp; &amp;nbsp; &amp;nbsp;Login Details&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;&lt;td style=&quot;width: 100%; padding-left: 20px; padding-right: 20px&quot;&gt;&lt;br&gt;Dear {0}  {1},&lt;br&gt;&lt;br&gt;&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;
        ///&lt;td style=&quot;width: 100%; padding-left: 20px; padding-right: 20px&quot;&gt;Thank you for r [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LMS Registration Login Details.
        /// </summary>
        public static string RegistrationDetails {
            get {
                return ResourceManager.GetString("RegistrationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table style=&quot;width: 100%&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///&lt;tbody&gt;&lt;tr&gt;&lt;td style=&quot;width: 10%&quot;&gt;&lt;/td&gt;&lt;td style=&quot;width: 80%&quot;&gt;
        ///&lt;table style=&quot;width: 100%;border: 1px solid #C3C3C5;border-radius: 10px;&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///&lt;tbody&gt;
        ///&lt;tr&gt;&lt;td style=&quot;width: 100%; padding-left: 20px; padding-right: 20px&quot;&gt;&lt;br&gt;Dear Admin,&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;&lt;td style=&quot;width: 100%; padding-left: 20px; padding-right: 20px&quot;&gt;&lt;br&gt;New User has been successfully registered to the LMS. &lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;&lt;td style=&quot;width: 100%; padding [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Registrationnoteficationtoadmin {
            get {
                return ResourceManager.GetString("Registrationnoteficationtoadmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User Details.
        /// </summary>
        public static string Registrationnoteficationtoadminsubjest {
            get {
                return ResourceManager.GetString("Registrationnoteficationtoadminsubjest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LMS Registration URL.
        /// </summary>
        public static string RegistrationUrl {
            get {
                return ResourceManager.GetString("RegistrationUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your reply has been Approved.
        /// </summary>
        public static string ReplyApproved {
            get {
                return ResourceManager.GetString("ReplyApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table style=&apos;font-family:Arial;font-size:9pt&apos;&gt;&lt;tr&gt;&lt;td&gt;Dear {0},&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td width=&apos;600px&apos;&gt;Your Reply has been {1} by admin for a thread&lt;table style=&apos;width: 600px&apos;&gt;&lt;tr&gt;&lt;td class=&apos;style2&apos; colspan=&apos;3&apos;&gt;&lt;b&gt;Details&lt;/b&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td style=&apos;width: 35%&apos;&gt;Thread Name&lt;/td&gt;&lt;td style=&apos;width: 2%&apos;&gt;     &lt;b&gt;:&lt;/b&gt;&lt;/td&gt;&lt;td style=&apos;width: 63%&apos;&gt;    {2}&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td style=&apos;width: 35%&apos;&gt; Your Reply&lt;/td&gt;&lt;td style=&apos;width: 2%&apos;&gt;&lt;b&gt;:&lt;/b&gt;&lt;/td&gt;&lt;td style=&apos;width: 63%&apos;&gt;       {3}&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt; Thanks and Re [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ReplyMaster {
            get {
                return ResourceManager.GetString("ReplyMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your reply has been Rejected.
        /// </summary>
        public static string ReplyRejected {
            get {
                return ResourceManager.GetString("ReplyRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request For joining group.
        /// </summary>
        public static string RequestGroup {
            get {
                return ResourceManager.GetString("RequestGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request for New Course.
        /// </summary>
        public static string RequestNewCourse {
            get {
                return ResourceManager.GetString("RequestNewCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table style=&quot;width: 100%;border: 1px solid #C3C3C5;border-radius: 10px;&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///&lt;tbody&gt;&lt;tr&gt;&lt;td style=&quot;width: 100%;background-color: #C3C3C5;height: 60px;color: #45748F;font-size: large;border-top-left-radius: 10px;border-top-right-radius: 10px;&quot;&gt;&amp;nbsp; &amp;nbsp; &amp;nbsp;Aseessment Details&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;&lt;td style=&quot;width: 100%; padding-left: 20px; padding-right: 20px&quot;&gt;&lt;br&gt;Dear User &lt;br&gt;&lt;br&gt;&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;
        ///&lt;td style=&quot;width: 100%; padding-left: 20px; padding-right: 20px&quot;&gt;Sheduled assee [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ScheduleAssessment {
            get {
                return ResourceManager.GetString("ScheduleAssessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table style=&apos;font-family: Arial; font-size: 9pt&apos;&gt;&lt;tr&gt;&lt;td style=&apos;font-family: Arial&apos;&gt;Dear&amp;nbsp;&amp;nbsp;{0},&lt;br /&gt;&lt;br /&gt;Please find details of your assessment mentioned below.&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;&amp;nbsp;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;&lt;table style=&apos;font-family: Arial; font-size: 9pt&apos;&gt;&lt;tr&gt;&lt;td style=&apos;font-family: Verdana&apos;&gt;Result&lt;/td&gt;&lt;td &gt;&lt;b&gt;:&lt;/b&gt;&lt;/td&gt;&lt;td style=&apos;font-family: Verdana&apos;&gt;{1}&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td style=&apos;font-family: Verdana&apos;&gt;Number Of Attempts Left&lt;/td&gt;&lt;td &gt;&lt;b&gt;:&lt;/b&gt;&lt;/td&gt;&lt;td style=&apos;font-family: Verdana&apos;&gt;{2}&lt;/td&gt;&lt;/tr&gt;&lt;/table [rest of string was truncated]&quot;;.
        /// </summary>
        public static string StudentQuestionPaper {
            get {
                return ResourceManager.GetString("StudentQuestionPaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription Details.
        /// </summary>
        public static string SubscriptionDetails {
            get {
                return ResourceManager.GetString("SubscriptionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br /&gt;&lt;table style=&apos;width: 100%&apos; cellpadding=&apos;0&apos; cellspacing=&apos;0&apos;&gt;
        ///&lt;tr&gt;&lt;td style=&apos;width: 10%&apos;&gt;&lt;/td&gt;&lt;td style=&apos;width: 80%&apos;&gt;
        ///&lt;table style=&apos;width: 100%;border: 1px solid #C3C3C5;border-radius: 10px;&apos; cellpadding=&apos;0&apos; cellspacing=&apos;0&apos;&gt;
        ///&lt;tr&gt;&lt;td style=&apos;width: 100%;background-color: #C3C3C5;height: 60px;color: #45748F;font-size: large;border-top-left-radius: 10px;border-top-right-radius: 10px;&apos;&gt;&amp;nbsp; &amp;nbsp; &amp;nbsp;Subscription Details&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;&lt;td style=&apos;width: 100%; padding-left: 20px; padding-right: 20px&apos;&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TenantSubscription {
            get {
                return ResourceManager.GetString("TenantSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table style=&quot;width: 100%&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///&lt;tbody&gt;&lt;tr&gt;&lt;td style=&quot;width: 10%&quot;&gt;&lt;/td&gt;&lt;td style=&quot;width: 80%&quot;&gt;
        ///&lt;br&gt;&lt;br&gt;&lt;table style=&quot;width: 100%;border: 1px solid #C3C3C5;border-radius: 10px;&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///&lt;tbody&gt;
        ///&lt;tr&gt;&lt;td style=&quot;width: 100%; padding-left: 20px; padding-right: 20px&quot;&gt;&lt;br&gt;Dear Trainer,&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;&lt;td style=&quot;width: 100%; padding-left: 20px; padding-right: 20px&quot;&gt;&lt;br&gt;&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;&lt;td style=&quot;width: 100%; padding-left: 20px; padding-right: 20px&quot;&gt;&lt;br&gt;User h [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ValidateAccessor {
            get {
                return ResourceManager.GetString("ValidateAccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tbody&gt;
        ///&lt;table style=&quot;width: 100%; border: 1px solid #C3C3C5; border-radius: 10px;&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///                            &lt;tr&gt;
        ///                                &lt;td style=&quot;width: 100%; background-color: #C3C3C5; height: 60px; color: #45748F; font-size: large; border-top-left-radius: 10px; border-top-right-radius: 10px;&quot;&gt;&amp;nbsp; &amp;nbsp; &amp;nbsp;VC Invitation&lt;/td&gt;
        ///                            &lt;/tr&gt;
        ///                            &lt;tr&gt;
        ///                                &lt;td style=&quot;width: 100%; p [rest of string was truncated]&quot;;.
        /// </summary>
        public static string VCRequest {
            get {
                return ResourceManager.GetString("VCRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table style=&quot;width: 100%;border: 1px solid #C3C3C5;border-radius: 10px;text-align:left;&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///&lt;tbody&gt;
        ///&lt;tr&gt;&lt;td style=&quot;width: 100%; padding-left: 20px; padding-right: 20px&quot;&gt;&lt;br&gt;Dear Admin,&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;&lt;td style=&quot;width: 100%; padding-left: 20px; padding-right: 20px&quot;&gt;&lt;br&gt;Need Approval for the {0} session scheduled to the Group {1}.&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;&lt;td style=&quot;width: 100%; padding-left: 20px; padding-right: 20px&quot;&gt;Please find the details below:&lt;/td&gt;&lt;/tr&gt;
        ///                        
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string VCRequestApproval {
            get {
                return ResourceManager.GetString("VCRequestApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VC request {0}.
        /// </summary>
        public static string VCRequestapprovalorrejSubjest {
            get {
                return ResourceManager.GetString("VCRequestapprovalorrejSubjest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VCRequest Approval.
        /// </summary>
        public static string VCRequestApprovalSubject {
            get {
                return ResourceManager.GetString("VCRequestApprovalSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table style=&quot;width: 100%;border: 1px solid #C3C3C5;border-radius: 10px;&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///&lt;tbody&gt;
        ///&lt;tr&gt;&lt;td style=&quot;width: 100%; padding-left: 20px; padding-right: 20px&quot;&gt;&lt;br&gt;Dear {0},&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;&lt;td style=&quot;width: 100%; padding-left: 20px; padding-right: 20px&quot;&gt;&lt;br&gt;Your Request has been {7} for the {1} session scheduled to the Group ({2})&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;&lt;td style=&quot;width: 100%; padding-left: 20px; padding-right: 20px&quot;&gt;Please find the details below:&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;&lt;td style=&quot;width: 100%; pad [rest of string was truncated]&quot;;.
        /// </summary>
        public static string VCRequestApproverOrRej {
            get {
                return ResourceManager.GetString("VCRequestApproverOrRej", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table style=&quot;width: 100%; border: 1px solid #C3C3C5; border-radius: 10px;&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///                            &lt;tbody&gt;&lt;tr&gt;
        ///                                &lt;td style=&quot;width: 100%; background-color: #C3C3C5; height: 60px; color: #45748F; font-size: large; border-top-left-radius: 10px; border-top-right-radius: 10px;&quot;&gt;&amp;nbsp; &amp;nbsp; &amp;nbsp;Manage Email IDs&lt;/td&gt;
        ///                            &lt;/tr&gt;
        ///                            &lt;tr&gt;
        ///                                &lt;td style=&quot;width: 100%;  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string VerifyEmailID {
            get {
                return ResourceManager.GetString("VerifyEmailID", resourceCulture);
            }
        }
    }
}
