//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsHub.API.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NITSMSTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NITSMSTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SportsHub.API.Resources.NITSMSTemplates", typeof(NITSMSTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear parent, Please make sure that your child attends the college on a regular basis. Your child&apos;s attendance for {0}. Regards, NIT Polytechnic, Nagpur..
        /// </summary>
        public static string Addendance {
            get {
                return ResourceManager.GetString("Addendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear parent {0} Today your ward was either absent or didn&apos;t attended all lectures. Please contact HoD. {1} NIT Polytechnic.
        /// </summary>
        public static string DailyAttendance {
            get {
                return ResourceManager.GetString("DailyAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear student, Your comment has been successfully submitted. Regards, NIT Polytechnic, Nagpur..
        /// </summary>
        public static string FeedbackSubmission {
            get {
                return ResourceManager.GetString("FeedbackSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Parents/Students, Your child&apos;s new class at NIT will begin on {0}. Before it&apos;s too late, confirm your admission. Regards, NIT Polytechnic, Nagpur..
        /// </summary>
        public static string NewBatch {
            get {
                return ResourceManager.GetString("NewBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear parents. Congratulations on your child’s graduation! We’re reaching out to remind you of the remaining balance for your child’s graduation gown that should be paid on the end of {0}. Please settle this account on or before the deadline to avoid delays. Regards, NIT Polytechnic, Nagpur..
        /// </summary>
        public static string PaymentPending {
            get {
                return ResourceManager.GetString("PaymentPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Parent/students, Your fee payment is due. This is friendly reminder to submit it and ignore it if you already process it. Total pending amount {0} Regards, NIT Polytechnic, Nagpur..
        /// </summary>
        public static string PaymentReminder {
            get {
                return ResourceManager.GetString("PaymentReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Parents/Students, Results for your child have been released; please visit the portal to view the result. Regards, NIT Polytechnic, Nagpur..
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Parents/Students, Your child’s final sessional/pre-board examination result for class is now available. To view them, login to your student portal here. URl: {0} Regards, NIT Polytechnic, Nagpur. .
        /// </summary>
        public static string ResultNotification {
            get {
                return ResourceManager.GetString("ResultNotification", resourceCulture);
            }
        }
    }
}
