//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsHub.API.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ScreenMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScreenMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SportsHub.API.Resources.ScreenMessage", typeof(ScreenMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add user to the Group..
        /// </summary>
        public static string AddUserFail {
            get {
                return ResourceManager.GetString("AddUserFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already in video conference session, Please close the browser and activate the link.
        /// </summary>
        public static string AlreadyActiveSession {
            get {
                return ResourceManager.GetString("AlreadyActiveSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already applied for this course..
        /// </summary>
        public static string AlreadyApplyed {
            get {
                return ResourceManager.GetString("AlreadyApplyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information already committed..
        /// </summary>
        public static string AlreadyCommitted {
            get {
                return ResourceManager.GetString("AlreadyCommitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exists..
        /// </summary>
        public static string AlreadyExists {
            get {
                return ResourceManager.GetString("AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please answer atleast one Feedback Question..
        /// </summary>
        public static string AnswerAtleastOneQuestion {
            get {
                return ResourceManager.GetString("AnswerAtleastOneQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog approved successfully.
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessment already created for this Course..
        /// </summary>
        public static string AssessmentAlreadyCreated {
            get {
                return ResourceManager.GetString("AssessmentAlreadyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigning Assessor was successful..
        /// </summary>
        public static string AssessorAssign {
            get {
                return ResourceManager.GetString("AssessorAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please assign Items..
        /// </summary>
        public static string AssignAgain {
            get {
                return ResourceManager.GetString("AssignAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atleast 1 question should be there to create an Assessment..
        /// </summary>
        public static string AtleastOneQuestion {
            get {
                return ResourceManager.GetString("AtleastOneQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size of attachments is restricted to {0} MB..
        /// </summary>
        public static string AttactmentSizeRestriction {
            get {
                return ResourceManager.GetString("AttactmentSizeRestriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt left is mandatory..
        /// </summary>
        public static string AttemptLeft {
            get {
                return ResourceManager.GetString("AttemptLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your post not sent for approval.
        /// </summary>
        public static string BlogNotSentForApproval {
            get {
                return ResourceManager.GetString("BlogNotSentForApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your post has been sent for approval.
        /// </summary>
        public static string BlogSentForApproval {
            get {
                return ResourceManager.GetString("BlogSentForApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can add a new topic only if you are assigned to any course..
        /// </summary>
        public static string CanAddTopicIfCourseAssigned {
            get {
                return ResourceManager.GetString("CanAddTopicIfCourseAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Inactivate the Role..
        /// </summary>
        public static string CannotInactivateRole {
            get {
                return ResourceManager.GetString("CannotInactivateRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot make Inactive as Schedule is already in use..
        /// </summary>
        public static string CannotInactiveSchedule {
            get {
                return ResourceManager.GetString("CannotInactiveSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot make Inactive as Chapter is already in use..
        /// </summary>
        public static string ChapterAlreadyUsed {
            get {
                return ResourceManager.GetString("ChapterAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please verify your email ID in order to make it Primary email ID.
        /// </summary>
        public static string CheckIsPrimary {
            get {
                return ResourceManager.GetString("CheckIsPrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code you entered is invalid..
        /// </summary>
        public static string CodeNotValid {
            get {
                return ResourceManager.GetString("CodeNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Commencement Date..
        /// </summary>
        public static string CommencementDate {
            get {
                return ResourceManager.GetString("CommencementDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Committed successfully..
        /// </summary>
        public static string CommitedSuccess {
            get {
                return ResourceManager.GetString("CommitedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication details already exists..
        /// </summary>
        public static string CommunicationExists {
            get {
                return ResourceManager.GetString("CommunicationExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete payment process to Post the Forum..
        /// </summary>
        public static string CompletePaymentToPost {
            get {
                return ResourceManager.GetString("CompletePaymentToPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please configure your site URL in web config..
        /// </summary>
        public static string ConfigureUrlInWebconfig {
            get {
                return ResourceManager.GetString("ConfigureUrlInWebconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Contact Details sent successfully..
        /// </summary>
        public static string ContactDetailSent {
            get {
                return ResourceManager.GetString("ContactDetailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to County with this name already exists..
        /// </summary>
        public static string CountryExists {
            get {
                return ResourceManager.GetString("CountryExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already applied for this course..
        /// </summary>
        public static string CourseAlreadyApplied {
            get {
                return ResourceManager.GetString("CourseAlreadyApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course already assigned to this Student..
        /// </summary>
        public static string CourseAlreadyAssigned {
            get {
                return ResourceManager.GetString("CourseAlreadyAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course with this name already exists.
        /// </summary>
        public static string CourseAlreadyExists {
            get {
                return ResourceManager.GetString("CourseAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course is already in use. Cannot change the status..
        /// </summary>
        public static string CourseAlreadyUsed {
            get {
                return ResourceManager.GetString("CourseAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User assigned for the course successfully.
        /// </summary>
        public static string CourseAssigned {
            get {
                return ResourceManager.GetString("CourseAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Duration cannot be Zero..
        /// </summary>
        public static string CourseDurationNotBeZero {
            get {
                return ResourceManager.GetString("CourseDurationNotBeZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your course creation limit permissions have been exceeded.Please contact Adminstrator.
        /// </summary>
        public static string CourseLimit {
            get {
                return ResourceManager.GetString("CourseLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course not assigned..
        /// </summary>
        public static string CourseNotAssigned {
            get {
                return ResourceManager.GetString("CourseNotAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot make Inactive as Trainer already in use..
        /// </summary>
        public static string CourseTrainerAlreadyUsed {
            get {
                return ResourceManager.GetString("CourseTrainerAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Survey created successfully..
        /// </summary>
        public static string CreateSurvey {
            get {
                return ResourceManager.GetString("CreateSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom URLs for the Tenant are generated..
        /// </summary>
        public static string CustomUrlGenerated {
            get {
                return ResourceManager.GetString("CustomUrlGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog Declined.
        /// </summary>
        public static string Decline {
            get {
                return ResourceManager.GetString("Decline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied to unshare the folder..
        /// </summary>
        public static string DeniedToUnshareFolder {
            get {
                return ResourceManager.GetString("DeniedToUnshareFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Dictionary Name already exists..
        /// </summary>
        public static string DictionaryExists {
            get {
                return ResourceManager.GetString("DictionaryExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth should not be greater than or equal to present date..
        /// </summary>
        public static string DOBNotGreaterThanPresentDate {
            get {
                return ResourceManager.GetString("DOBNotGreaterThanPresentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration restricted for below 15 years..
        /// </summary>
        public static string DobValidation {
            get {
                return ResourceManager.GetString("DobValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can upload only pdf, pptx and doc files..
        /// </summary>
        public static string DocFileType {
            get {
                return ResourceManager.GetString("DocFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title already exist.
        /// </summary>
        public static string DuplicateTitle {
            get {
                return ResourceManager.GetString("DuplicateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration From should be less than Duration To..
        /// </summary>
        public static string DurationFromLessThanDurationTo {
            get {
                return ResourceManager.GetString("DurationFromLessThanDurationTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail sent successfully..
        /// </summary>
        public static string EmailSent {
            get {
                return ResourceManager.GetString("EmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select End Date..
        /// </summary>
        public static string EndDateIsNull {
            get {
                return ResourceManager.GetString("EndDateIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time must be greater than Current Time..
        /// </summary>
        public static string EndTimeGreaterThanCurrentTime {
            get {
                return ResourceManager.GetString("EndTimeGreaterThanCurrentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time must be greater than Start Time..
        /// </summary>
        public static string EndTimeGreaterThanStartTime {
            get {
                return ResourceManager.GetString("EndTimeGreaterThanStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No assessments found for your login.
        /// </summary>
        public static string EnrollCourse {
            get {
                return ResourceManager.GetString("EnrollCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter all mandatory fields..
        /// </summary>
        public static string EnterAllMandatory {
            get {
                return ResourceManager.GetString("EnterAllMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Duration..
        /// </summary>
        public static string EnterCourseDuration {
            get {
                return ResourceManager.GetString("EnterCourseDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Email address..
        /// </summary>
        public static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter No. of sessions..
        /// </summary>
        public static string EnterSession {
            get {
                return ResourceManager.GetString("EnterSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Task Url.
        /// </summary>
        public static string EnterTaskUrl {
            get {
                return ResourceManager.GetString("EnterTaskUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter some text to search..
        /// </summary>
        public static string EnterTextToSearch {
            get {
                return ResourceManager.GetString("EnterTextToSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter No. of URLs..
        /// </summary>
        public static string EnterUrls {
            get {
                return ResourceManager.GetString("EnterUrls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid Password..
        /// </summary>
        public static string EnterValidPassword {
            get {
                return ResourceManager.GetString("EnterValidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid User Name..
        /// </summary>
        public static string EnterValidUsername {
            get {
                return ResourceManager.GetString("EnterValidUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occurred, please check..
        /// </summary>
        public static string ErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Request already exists..
        /// </summary>
        public static string EventRequestExists {
            get {
                return ResourceManager.GetString("EventRequestExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Request has been raised successfully and sent for Admin approval..
        /// </summary>
        public static string EventRequestPopUp {
            get {
                return ResourceManager.GetString("EventRequestPopUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event request is already {0}.
        /// </summary>
        public static string EventRequestStatus {
            get {
                return ResourceManager.GetString("EventRequestStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam Name already exists..
        /// </summary>
        public static string ExamNameExists {
            get {
                return ResourceManager.GetString("ExamNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel file successfully processed and no records are imported..
        /// </summary>
        public static string ExcelProcessedNotImported {
            get {
                return ResourceManager.GetString("ExcelProcessedNotImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback details submitted successfully..
        /// </summary>
        public static string FeedackSubmitted {
            get {
                return ResourceManager.GetString("FeedackSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already submitted the Feedback..
        /// </summary>
        public static string FeedbackAlreadySubmitted {
            get {
                return ResourceManager.GetString("FeedbackAlreadySubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already given your feedback..
        /// </summary>
        public static string Feedbackdone {
            get {
                return ResourceManager.GetString("Feedbackdone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback question already exists. .
        /// </summary>
        public static string FeedbackQuestionExists {
            get {
                return ResourceManager.GetString("FeedbackQuestionExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File deleted successfully..
        /// </summary>
        public static string FileDeleted {
            get {
                return ResourceManager.GetString("FileDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, no file exists in the database with this name..
        /// </summary>
        public static string FileNotExists {
            get {
                return ResourceManager.GetString("FileNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found..
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload pdf,ppt,xls,txt,gif,jpd,jpeg and doc file formats only..
        /// </summary>
        public static string FileTypeToUpload {
            get {
                return ResourceManager.GetString("FileTypeToUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill the Course Schedule details.
        /// </summary>
        public static string FillCourseSchedule {
            get {
                return ResourceManager.GetString("FillCourseSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Assignment for this course already exists.
        /// </summary>
        public static string FinalAssessmentalExists {
            get {
                return ResourceManager.GetString("FinalAssessmentalExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessment already sent for evaluation..
        /// </summary>
        public static string FinalExamPending {
            get {
                return ResourceManager.GetString("FinalExamPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already passed your Final Assessment..
        /// </summary>
        public static string FinalPassed {
            get {
                return ResourceManager.GetString("FinalPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload Flash files only..
        /// </summary>
        public static string FlashFile {
            get {
                return ResourceManager.GetString("FlashFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder deleted successfully..
        /// </summary>
        public static string FolderDeleted {
            get {
                return ResourceManager.GetString("FolderDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum Topic created successfully..
        /// </summary>
        public static string ForumCreated {
            get {
                return ResourceManager.GetString("ForumCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum Topic created successfully and sent for Admin approval..
        /// </summary>
        public static string ForumInformationSaved {
            get {
                return ResourceManager.GetString("ForumInformationSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Gateway configuration is missing.
        /// </summary>
        public static string Gateway {
            get {
                return ResourceManager.GetString("Gateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To Forgot Password Screen !!!.
        /// </summary>
        public static string GotoForgotPassword {
            get {
                return ResourceManager.GetString("GotoForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Name you entered already exists..
        /// </summary>
        public static string GroupExists {
            get {
                return ResourceManager.GetString("GroupExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile image size limited to 1 MB..
        /// </summary>
        public static string ImageSizeLimit {
            get {
                return ResourceManager.GetString("ImageSizeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select GIF, PNG, JPEG, JPG, BMP files only..
        /// </summary>
        public static string ImageType {
            get {
                return ResourceManager.GetString("ImageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information deleted successfully..
        /// </summary>
        public static string InformationDeleted {
            get {
                return ResourceManager.GetString("InformationDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information already exists..
        /// </summary>
        public static string InformationExists {
            get {
                return ResourceManager.GetString("InformationExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information not deleted..
        /// </summary>
        public static string InformationNotDeleted {
            get {
                return ResourceManager.GetString("InformationNotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information not saved..
        /// </summary>
        public static string InformationNotSaved {
            get {
                return ResourceManager.GetString("InformationNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your post is not saved in drafts.
        /// </summary>
        public static string InformationNotSavedInDrafts {
            get {
                return ResourceManager.GetString("InformationNotSavedInDrafts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information not updated..
        /// </summary>
        public static string InformationNotUpdated {
            get {
                return ResourceManager.GetString("InformationNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information saved successfully..
        /// </summary>
        public static string InformationSaved {
            get {
                return ResourceManager.GetString("InformationSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your post has been successfully saved in drafts.
        /// </summary>
        public static string InformationSavedInDrafts {
            get {
                return ResourceManager.GetString("InformationSavedInDrafts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your information has been successfully sent to your Email Id..
        /// </summary>
        public static string InformationSentToEmail {
            get {
                return ResourceManager.GetString("InformationSentToEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information updated successfully..
        /// </summary>
        public static string InformationUpdated {
            get {
                return ResourceManager.GetString("InformationUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already passed your Internal Assessment..
        /// </summary>
        public static string InternalExamAlreadyPass {
            get {
                return ResourceManager.GetString("InternalExamAlreadyPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Assessment is mandatory to take Final Exam..
        /// </summary>
        public static string InternalExamManditary {
            get {
                return ResourceManager.GetString("InternalExamManditary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User Name/Password, Please try again..
        /// </summary>
        public static string InvalidUsernamePassword {
            get {
                return ResourceManager.GetString("InvalidUsernamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product license has been expired..
        /// </summary>
        public static string IsExpired {
            get {
                return ResourceManager.GetString("IsExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new Issue added successfully..
        /// </summary>
        public static string IssueAdded {
            get {
                return ResourceManager.GetString("IssueAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request for joining this group has already queued..
        /// </summary>
        public static string JoiningRequestQueued {
            get {
                return ResourceManager.GetString("JoiningRequestQueued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for joining the group. A request has been sent to Admin for Approval..
        /// </summary>
        public static string JoiningRequestSent {
            get {
                return ResourceManager.GetString("JoiningRequestSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Allocation updated successfully..
        /// </summary>
        public static string LanguageAllocationUpdatr {
            get {
                return ResourceManager.GetString("LanguageAllocationUpdatr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Language already allocated..
        /// </summary>
        public static string LanguageAlreadyAllocated {
            get {
                return ResourceManager.GetString("LanguageAlreadyAllocated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last used year should be less than or equals to current year..
        /// </summary>
        public static string LastUsedyearLessThanCurrentYear {
            get {
                return ResourceManager.GetString("LastUsedyearLessThanCurrentYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change the status as Location already in use..
        /// </summary>
        public static string LocationAlreadyUsed {
            get {
                return ResourceManager.GetString("LocationAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Name with this already exists..
        /// </summary>
        public static string LocationExists {
            get {
                return ResourceManager.GetString("LocationExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Login to add a New Topic..
        /// </summary>
        public static string LoginToAddTopic {
            get {
                return ResourceManager.GetString("LoginToAddTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Login to Reply..
        /// </summary>
        public static string LoginToReply {
            get {
                return ResourceManager.GetString("LoginToReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail permanently deleted..
        /// </summary>
        public static string MailDeleted {
            get {
                return ResourceManager.GetString("MailDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete mail..
        /// </summary>
        public static string MailDeleteFail {
            get {
                return ResourceManager.GetString("MailDeleteFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail sent failed..
        /// </summary>
        public static string MailFail {
            get {
                return ResourceManager.GetString("MailFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected mails are marked as read..
        /// </summary>
        public static string MailMarkedRead {
            get {
                return ResourceManager.GetString("MailMarkedRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to mark as read..
        /// </summary>
        public static string MailMarkedReadFail {
            get {
                return ResourceManager.GetString("MailMarkedReadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected mails is deleted permanently..
        /// </summary>
        public static string MailSelectedDeleted {
            get {
                return ResourceManager.GetString("MailSelectedDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected mails is moved to Trash..
        /// </summary>
        public static string MailSelectedTrashed {
            get {
                return ResourceManager.GetString("MailSelectedTrashed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Sent successfully..
        /// </summary>
        public static string MailSuccess {
            get {
                return ResourceManager.GetString("MailSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail has been moved to trash..
        /// </summary>
        public static string MailTrashed {
            get {
                return ResourceManager.GetString("MailTrashed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eligiblity does not meet..
        /// </summary>
        public static string MaterialEligiblity {
            get {
                return ResourceManager.GetString("MaterialEligiblity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material with this name already exists for the particular course you selected..
        /// </summary>
        public static string MaterialExists {
            get {
                return ResourceManager.GetString("MaterialExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material uploaded successfully..
        /// </summary>
        public static string MaterialUploaded {
            get {
                return ResourceManager.GetString("MaterialUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum only 2 Address details can be added..
        /// </summary>
        public static string MaximumNoAddressDetails {
            get {
                return ResourceManager.GetString("MaximumNoAddressDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum age should be above 18 years to register..
        /// </summary>
        public static string MinimumAge {
            get {
                return ResourceManager.GetString("MinimumAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully assigned for applied course..
        /// </summary>
        public static string NewCourseApproval {
            get {
                return ResourceManager.GetString("NewCourseApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News with this Headline already exists..
        /// </summary>
        public static string NewsExists {
            get {
                return ResourceManager.GetString("NewsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No assessment have been created.
        /// </summary>
        public static string Noassessment {
            get {
                return ResourceManager.GetString("Noassessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Blogs avilable for you..
        /// </summary>
        public static string NoBlogs {
            get {
                return ResourceManager.GetString("NoBlogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessment not available for this chapter. First create Post assessment for this chapter..
        /// </summary>
        public static string NoChapterAssessment {
            get {
                return ResourceManager.GetString("NoChapterAssessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Details available..
        /// </summary>
        public static string NoDetails {
            get {
                return ResourceManager.GetString("NoDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Feedback questions available..
        /// </summary>
        public static string NoFeedback {
            get {
                return ResourceManager.GetString("NoFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Final Exam has been created.
        /// </summary>
        public static string NoFinalAssessment {
            get {
                return ResourceManager.GetString("NoFinalAssessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Final Assessment result found..
        /// </summary>
        public static string NoFinalAssessmentFound {
            get {
                return ResourceManager.GetString("NoFinalAssessmentFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Final Exam has been created.
        /// </summary>
        public static string NoFinalExamCreated {
            get {
                return ResourceManager.GetString("NoFinalExamCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Internal Assessment has been created.
        /// </summary>
        public static string NoInternalexamcreated {
            get {
                return ResourceManager.GetString("NoInternalexamcreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Items to move..
        /// </summary>
        public static string NoItemsToMove {
            get {
                return ResourceManager.GetString("NoItemsToMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No mails available to delete..
        /// </summary>
        public static string NoMail {
            get {
                return ResourceManager.GetString("NoMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No materials available for the selected course..
        /// </summary>
        public static string Nomaterial {
            get {
                return ResourceManager.GetString("Nomaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. of Questions should not exceed more than {0}..
        /// </summary>
        public static string NoOfQuestionNotExceed {
            get {
                return ResourceManager.GetString("NoOfQuestionNotExceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No of Questions should be equal to sum of objective and subjective questions.
        /// </summary>
        public static string NoofQuestions {
            get {
                return ResourceManager.GetString("NoofQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No of {0} Questions available are {1}..
        /// </summary>
        public static string NoofSubjectiveQuestionsExceed {
            get {
                return ResourceManager.GetString("NoofSubjectiveQuestionsExceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Poll question available..
        /// </summary>
        public static string NoPolls {
            get {
                return ResourceManager.GetString("NoPolls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Post Assessment have been created..
        /// </summary>
        public static string NoPostTrainingAssessmentCreated {
            get {
                return ResourceManager.GetString("NoPostTrainingAssessmentCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records are Imported..
        /// </summary>
        public static string NoRecordImported {
            get {
                return ResourceManager.GetString("NoRecordImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records to display..
        /// </summary>
        public static string NoRecords {
            get {
                return ResourceManager.GetString("NoRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Reply available for this topic..
        /// </summary>
        public static string NoReply {
            get {
                return ResourceManager.GetString("NoReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Survey questions available..
        /// </summary>
        public static string NoSurveyQuestion {
            get {
                return ResourceManager.GetString("NoSurveyQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add atleast one question to publish survey..
        /// </summary>
        public static string NoSurveyQuestionsAvilable {
            get {
                return ResourceManager.GetString("NoSurveyQuestionsAvilable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not upload exe,dll and sln files..
        /// </summary>
        public static string NotUploadExeDllSln {
            get {
                return ResourceManager.GetString("NotUploadExeDllSln", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid request..
        /// </summary>
        public static string NotValid {
            get {
                return ResourceManager.GetString("NotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No meeting request available with the given link.
        /// </summary>
        public static string NoVCRequestAvailable {
            get {
                return ResourceManager.GetString("NoVCRequestAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password is incorrect..
        /// </summary>
        public static string OldPasswordNotMatched {
            get {
                return ResourceManager.GetString("OldPasswordNotMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option{0} is already exists..
        /// </summary>
        public static string OptionExists {
            get {
                return ResourceManager.GetString("OptionExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Organization Logo.
        /// </summary>
        public static string OrganizationLogo {
            get {
                return ResourceManager.GetString("OrganizationLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year of passing should be less than or equals to current year..
        /// </summary>
        public static string PassingYearNotLessThanCurrentYear {
            get {
                return ResourceManager.GetString("PassingYearNotLessThanCurrentYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already passed your post assessment..
        /// </summary>
        public static string PassPost {
            get {
                return ResourceManager.GetString("PassPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed successful..
        /// </summary>
        public static string PasswordChanged {
            get {
                return ResourceManager.GetString("PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password  doesn&apos;t match with Confirm Password..
        /// </summary>
        public static string PasswordNotMatched {
            get {
                return ResourceManager.GetString("PasswordNotMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Password has been sent to your registered email ID..
        /// </summary>
        public static string PasswordSentToEmail {
            get {
                return ResourceManager.GetString("PasswordSentToEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password change unsuccessful..
        /// </summary>
        public static string PasswordUnchanged {
            get {
                return ResourceManager.GetString("PasswordUnchanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please do payment to take {0} for this course..
        /// </summary>
        public static string Paymentrequired {
            get {
                return ResourceManager.GetString("Paymentrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You dont have permission to this URL..
        /// </summary>
        public static string PermissionCheck {
            get {
                return ResourceManager.GetString("PermissionCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poll created successfully..
        /// </summary>
        public static string PollCreated {
            get {
                return ResourceManager.GetString("PollCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date should be greater than today to modify a poll..
        /// </summary>
        public static string PollEdit {
            get {
                return ResourceManager.GetString("PollEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poll with this name already exists for the selected Course for  the selected Dates..
        /// </summary>
        public static string PollExists {
            get {
                return ResourceManager.GetString("PollExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poll question already exists..
        /// </summary>
        public static string PollQuestionExists {
            get {
                return ResourceManager.GetString("PollQuestionExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poll submitted successfully..
        /// </summary>
        public static string PollsSubmitted {
            get {
                return ResourceManager.GetString("PollsSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to post a comment.
        /// </summary>
        public static string Postnotsaved {
            get {
                return ResourceManager.GetString("Postnotsaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information posted successfully.
        /// </summary>
        public static string PostSaved {
            get {
                return ResourceManager.GetString("PostSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set minimum pass percentage.
        /// </summary>
        public static string PracticalPasspercentage {
            get {
                return ResourceManager.GetString("PracticalPasspercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Assessment test is mandatory for this course..
        /// </summary>
        public static string PreAssessmentMandatory {
            get {
                return ResourceManager.GetString("PreAssessmentMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please do Pre Assessment to apply for this course..
        /// </summary>
        public static string PreassessmentManditary {
            get {
                return ResourceManager.GetString("PreassessmentManditary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre Assessment for the Course is mandatory. Please attempt that first..
        /// </summary>
        public static string PreTestMandatory {
            get {
                return ResourceManager.GetString("PreTestMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your primary Email has been changed.The Activation link will be sent to the new EmailID.Please click  the link in that email to continue..
        /// </summary>
        public static string Primarytrue {
            get {
                return ResourceManager.GetString("Primarytrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blogs Published Successfully.
        /// </summary>
        public static string PublishBlog {
            get {
                return ResourceManager.GetString("PublishBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey Published successfully..
        /// </summary>
        public static string PublishSurvey {
            get {
                return ResourceManager.GetString("PublishSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This question already exists for the selected Course and Chapter..
        /// </summary>
        public static string QuestionExists {
            get {
                return ResourceManager.GetString("QuestionExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This question already exists for the selected Course..
        /// </summary>
        public static string QuestionforinternalassessmentExists {
            get {
                return ResourceManager.GetString("QuestionforinternalassessmentExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can raise issue after assigning to the course..
        /// </summary>
        public static string RaiseIssueAfterCourseAssigned {
            get {
                return ResourceManager.GetString("RaiseIssueAfterCourseAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record archived successfully..
        /// </summary>
        public static string RecordArchived {
            get {
                return ResourceManager.GetString("RecordArchived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record cannot be archived..
        /// </summary>
        public static string RecordCannotArchived {
            get {
                return ResourceManager.GetString("RecordCannotArchived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is framework level role, record cannot be edited..
        /// </summary>
        public static string RecordCannotEdit {
            get {
                return ResourceManager.GetString("RecordCannotEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record cannot be rollback..
        /// </summary>
        public static string RecordCannotRollback {
            get {
                return ResourceManager.GetString("RecordCannotRollback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record deleted successfully..
        /// </summary>
        public static string RecordDeleted {
            get {
                return ResourceManager.GetString("RecordDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record rollback successfully..
        /// </summary>
        public static string RecordRollbacked {
            get {
                return ResourceManager.GetString("RecordRollbacked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to register, please contact Administrator..
        /// </summary>
        public static string RegistrationFailSmtp {
            get {
                return ResourceManager.GetString("RegistrationFailSmtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration for LMS is successful..
        /// </summary>
        public static string RegistrationSuccessful {
            get {
                return ResourceManager.GetString("RegistrationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply sent successfully..
        /// </summary>
        public static string ReplySent {
            get {
                return ResourceManager.GetString("ReplySent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply submitted successfully..
        /// </summary>
        public static string ReplySubmitted {
            get {
                return ResourceManager.GetString("ReplySubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Html &amp; Xml code are not allowed. Please provide text without &lt; and &gt;..
        /// </summary>
        public static string RequestValidationError {
            get {
                return ResourceManager.GetString("RequestValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Room already allocated for another batch..
        /// </summary>
        public static string RoomAlreadyAssigned {
            get {
                return ResourceManager.GetString("RoomAlreadyAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room No with this already exists for that Location..
        /// </summary>
        public static string RoomAlreadyExists {
            get {
                return ResourceManager.GetString("RoomAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change the status as Room already in use..
        /// </summary>
        public static string RoomAlreadyUsed {
            get {
                return ResourceManager.GetString("RoomAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please save the details before commiting..
        /// </summary>
        public static string SaveBeforeCommiting {
            get {
                return ResourceManager.GetString("SaveBeforeCommiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already applied for this Course..
        /// </summary>
        public static string ScheduleAlreadyApplied {
            get {
                return ResourceManager.GetString("ScheduleAlreadyApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule is already assigned for the Trainer..
        /// </summary>
        public static string ScheduleAlreadyAssigned {
            get {
                return ResourceManager.GetString("ScheduleAlreadyAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Course Category before selecting checkbox..
        /// </summary>
        public static string SelectCategory {
            get {
                return ResourceManager.GetString("SelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Chapter Name..
        /// </summary>
        public static string SelectChapterName {
            get {
                return ResourceManager.GetString("SelectChapterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Course before selecting Date..
        /// </summary>
        public static string SelectCourse {
            get {
                return ResourceManager.GetString("SelectCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Course..
        /// </summary>
        public static string SelectCourseName {
            get {
                return ResourceManager.GetString("SelectCourseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the correct Excel Template..
        /// </summary>
        public static string SelectCurrectExcel {
            get {
                return ResourceManager.GetString("SelectCurrectExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Correct Option..
        /// </summary>
        public static string SelectCurrectOption {
            get {
                return ResourceManager.GetString("SelectCurrectOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Date..
        /// </summary>
        public static string SelectDate {
            get {
                return ResourceManager.GetString("SelectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected folder is shared with the Group..
        /// </summary>
        public static string SelectedFolderShared {
            get {
                return ResourceManager.GetString("SelectedFolderShared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected User has been successfully added to the Group..
        /// </summary>
        public static string SelectedUserAdded {
            get {
                return ResourceManager.GetString("SelectedUserAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the Excel File  (Eg: Excel.xlsx)..
        /// </summary>
        public static string SelectExcelFile {
            get {
                return ResourceManager.GetString("SelectExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a file to upload..
        /// </summary>
        public static string SelectFileUpload {
            get {
                return ResourceManager.GetString("SelectFileUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Forms to assign..
        /// </summary>
        public static string SelectFormToAssign {
            get {
                return ResourceManager.GetString("SelectFormToAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Forms to remove..
        /// </summary>
        public static string SelectFormToRemove {
            get {
                return ResourceManager.GetString("SelectFormToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Group to send mail..
        /// </summary>
        public static string SelectGroup {
            get {
                return ResourceManager.GetString("SelectGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select GIF,PNG,JPEG,JPG,BMP files only.
        /// </summary>
        public static string SelectImage {
            get {
                return ResourceManager.GetString("SelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Location to assign..
        /// </summary>
        public static string SelectLocationToAssign {
            get {
                return ResourceManager.GetString("SelectLocationToAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Location to Remove..
        /// </summary>
        public static string SelectLocationToRemove {
            get {
                return ResourceManager.GetString("SelectLocationToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select atleast one mail..
        /// </summary>
        public static string SelectMail {
            get {
                return ResourceManager.GetString("SelectMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please assign at least one material to chapter..
        /// </summary>
        public static string SelectOneMaterial {
            get {
                return ResourceManager.GetString("SelectOneMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select any one option..
        /// </summary>
        public static string SelectOption {
            get {
                return ResourceManager.GetString("SelectOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Poll question..
        /// </summary>
        public static string SelectPoll {
            get {
                return ResourceManager.GetString("SelectPoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Profile Picture..
        /// </summary>
        public static string SelectProfilePicture {
            get {
                return ResourceManager.GetString("SelectProfilePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Tasks to assign..
        /// </summary>
        public static string SelectTaskToAssign {
            get {
                return ResourceManager.GetString("SelectTaskToAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Tasks to remove..
        /// </summary>
        public static string SelectTaskToRemove {
            get {
                return ResourceManager.GetString("SelectTaskToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Tenant..
        /// </summary>
        public static string SelectTenant {
            get {
                return ResourceManager.GetString("SelectTenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select atleast one user to take the Attendance..
        /// </summary>
        public static string SelectUser {
            get {
                return ResourceManager.GetString("SelectUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to send Email, please contact Administator..
        /// </summary>
        public static string SendEmailError {
            get {
                return ResourceManager.GetString("SendEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already logged in. Do you want to disconnect your previous session?.
        /// </summary>
        public static string SessionConnect {
            get {
                return ResourceManager.GetString("SessionConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session is disconnected as another user logged in with the same credentials. Try to login again..
        /// </summary>
        public static string SessionDisconnect {
            get {
                return ResourceManager.GetString("SessionDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. of sessions should not be 0..
        /// </summary>
        public static string SessionsNotBeZero {
            get {
                return ResourceManager.GetString("SessionsNotBeZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared folder cannot be deleted..
        /// </summary>
        public static string SharedFolderCannotDeleted {
            get {
                return ResourceManager.GetString("SharedFolderCannotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared permission for the selectd folder is removed..
        /// </summary>
        public static string SharedPermissionRemoves {
            get {
                return ResourceManager.GetString("SharedPermissionRemoves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to send Email, please contact Administrator..
        /// </summary>
        public static string SmtpConfigurationNotExist {
            get {
                return ResourceManager.GetString("SmtpConfigurationNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space is not allowed to Save..
        /// </summary>
        public static string SpaceNotAccepted {
            get {
                return ResourceManager.GetString("SpaceNotAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date should not be greater than End Date..
        /// </summary>
        public static string StartDateNotGreaterThanEndDate {
            get {
                return ResourceManager.GetString("StartDateNotGreaterThanEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Start Date.
        /// </summary>
        public static string StartDateNotSelected {
            get {
                return ResourceManager.GetString("StartDateNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date should be greater than End Date..
        /// </summary>
        public static string StartDateShouldGreaterThanEndDate {
            get {
                return ResourceManager.GetString("StartDateShouldGreaterThanEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time must be greater than Current Time..
        /// </summary>
        public static string StartTimeGreaterThanCurrentTime {
            get {
                return ResourceManager.GetString("StartTimeGreaterThanCurrentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time should not be greater than End Time..
        /// </summary>
        public static string StartTimeNotGreaterThanEndTime {
            get {
                return ResourceManager.GetString("StartTimeNotGreaterThanEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student has not updated Email ID..
        /// </summary>
        public static string StudentNotUpdateEmailID {
            get {
                return ResourceManager.GetString("StudentNotUpdateEmailID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub County with this name already exists..
        /// </summary>
        public static string SubCountryExists {
            get {
                return ResourceManager.GetString("SubCountryExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your no. of user accounts has been consumed..
        /// </summary>
        public static string SubscriptionAccountConsumed {
            get {
                return ResourceManager.GetString("SubscriptionAccountConsumed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. of accounts left for the subscription are {0}..
        /// </summary>
        public static string SubscriptionAccountsLeft {
            get {
                return ResourceManager.GetString("SubscriptionAccountsLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription activated Successfully..
        /// </summary>
        public static string SubscriptionActivate {
            get {
                return ResourceManager.GetString("SubscriptionActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant subscription De-Activated successfully..
        /// </summary>
        public static string SubscriptionDeavtivated {
            get {
                return ResourceManager.GetString("SubscriptionDeavtivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Tenant is Super Admin, cannot change the status to Inactive..
        /// </summary>
        public static string SuperAdminCannotBeChanged {
            get {
                return ResourceManager.GetString("SuperAdminCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already submitted the Survey..
        /// </summary>
        public static string SurveyAlreadySubmitted {
            get {
                return ResourceManager.GetString("SurveyAlreadySubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey end date should be greater than or equal to today’s date..
        /// </summary>
        public static string SurveyEndDate {
            get {
                return ResourceManager.GetString("SurveyEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey with this name already exists for the selected Course for  the selected Dates..
        /// </summary>
        public static string SurveyExists {
            get {
                return ResourceManager.GetString("SurveyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey Or Poll Already exist for selected date..
        /// </summary>
        public static string SurveyPollDateCheck {
            get {
                return ResourceManager.GetString("SurveyPollDateCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey question already exists..
        /// </summary>
        public static string SurveyQuestionExists {
            get {
                return ResourceManager.GetString("SurveyQuestionExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey start date should be greater than todays date..
        /// </summary>
        public static string SurveyStartDate {
            get {
                return ResourceManager.GetString("SurveyStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At present this Tenant is Inactive, please contact administrator..
        /// </summary>
        public static string TenantInactive {
            get {
                return ResourceManager.GetString("TenantInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant is not yet mapped to any Subscription..
        /// </summary>
        public static string TenantNotMappedToSubscription {
            get {
                return ResourceManager.GetString("TenantNotMappedToSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for taking the exam, please click on the End button to submit your answers.
        ///Do NOT refresh the page or use the back button on the browser..
        /// </summary>
        public static string ThankForTakingExam {
            get {
                return ResourceManager.GetString("ThankForTakingExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread Locked successfully..
        /// </summary>
        public static string ThreadLocked {
            get {
                return ResourceManager.GetString("ThreadLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread Unlocked successfully..
        /// </summary>
        public static string ThreadUnlocked {
            get {
                return ResourceManager.GetString("ThreadUnlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This time already utilized..
        /// </summary>
        public static string TimeAlreadyUtilized {
            get {
                return ResourceManager.GetString("TimeAlreadyUtilized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete your course study duration time..
        /// </summary>
        public static string TimeStudy {
            get {
                return ResourceManager.GetString("TimeStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter To Mail address..
        /// </summary>
        public static string ToMail {
            get {
                return ResourceManager.GetString("ToMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Forum Topic already exists fot the selected course..
        /// </summary>
        public static string TopicExists {
            get {
                return ResourceManager.GetString("TopicExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainer is already assigned to the Course..
        /// </summary>
        public static string TrainerAlreadyAssignedToCourse {
            get {
                return ResourceManager.GetString("TrainerAlreadyAssignedToCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainer already allocated to the Schedule for the selected Date and Time..
        /// </summary>
        public static string TrainerAlreadyScheduled {
            get {
                return ResourceManager.GetString("TrainerAlreadyScheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainer End Date should not be greater than Schedule End Date..
        /// </summary>
        public static string TrainerEndDateNotGreaterThanScheduleEndDate {
            get {
                return ResourceManager.GetString("TrainerEndDateNotGreaterThanScheduleEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainer End Time should not be greater than Schedule End Time..
        /// </summary>
        public static string TrainerEndTimeNotGreaterThanScheduleEndTime {
            get {
                return ResourceManager.GetString("TrainerEndTimeNotGreaterThanScheduleEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainer Start Date should not be greater than Trainer End Date..
        /// </summary>
        public static string TrainerStartDateNotGreaterThanEndDate {
            get {
                return ResourceManager.GetString("TrainerStartDateNotGreaterThanEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainer Start Date should not be less than Schedule Start Date..
        /// </summary>
        public static string TrainerStartDateNotLessThanScheduleStartDate {
            get {
                return ResourceManager.GetString("TrainerStartDateNotLessThanScheduleStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainer Start Time should not be greater than Trainer End Time..
        /// </summary>
        public static string TrainerStartTimeNotGreaterThanEndTime {
            get {
                return ResourceManager.GetString("TrainerStartTimeNotGreaterThanEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainer Start Time should not be less than Schedule Start Time..
        /// </summary>
        public static string TrainerStartTimeNotLessThanScheduleStartTime {
            get {
                return ResourceManager.GetString("TrainerStartTimeNotLessThanScheduleStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again..
        /// </summary>
        public static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to assign Assessor..
        /// </summary>
        public static string UnableToAssignAssessor {
            get {
                return ResourceManager.GetString("UnableToAssignAssessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to join the Group..
        /// </summary>
        public static string UnableToJoin {
            get {
                return ResourceManager.GetString("UnableToJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to process the VC Request..
        /// </summary>
        public static string UnableToProcessVcRequest {
            get {
                return ResourceManager.GetString("UnableToProcessVcRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retreive Password..
        /// </summary>
        public static string UnableToRetreivePassword {
            get {
                return ResourceManager.GetString("UnableToRetreivePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save the content to Pdf..
        /// </summary>
        public static string UnableToSavedPDF {
            get {
                return ResourceManager.GetString("UnableToSavedPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to share the selected folder with the Group..
        /// </summary>
        public static string UnableToShareFolder {
            get {
                return ResourceManager.GetString("UnableToShareFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to access this application..
        /// </summary>
        public static string UnAuthoriseduserForApp {
            get {
                return ResourceManager.GetString("UnAuthoriseduserForApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You dont have privilege to access this page..
        /// </summary>
        public static string UnauthorizedUser {
            get {
                return ResourceManager.GetString("UnauthorizedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming Event with this Headline already exists..
        /// </summary>
        public static string UpcomingEventExists {
            get {
                return ResourceManager.GetString("UpcomingEventExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Urls for subscription account already generated..
        /// </summary>
        public static string UrlSubscriptionAlreadyGenerated {
            get {
                return ResourceManager.GetString("UrlSubscriptionAlreadyGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve data, please contact Administrator..
        /// </summary>
        public static string UserDataError {
            get {
                return ResourceManager.GetString("UserDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Group cannot be student..
        /// </summary>
        public static string UsergroupNotBeStudent {
            get {
                return ResourceManager.GetString("UsergroupNotBeStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Rejected successfully..
        /// </summary>
        public static string UserRejected {
            get {
                return ResourceManager.GetString("UserRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been removed from this Group..
        /// </summary>
        public static string UserRemoved {
            get {
                return ResourceManager.GetString("UserRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practical percentage cannot be 0.
        /// </summary>
        public static string ValidatePracticalPercentage {
            get {
                return ResourceManager.GetString("ValidatePracticalPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of Theory and Practical percentage should be 100.
        /// </summary>
        public static string ValidateTheoryLab {
            get {
                return ResourceManager.GetString("ValidateTheoryLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Course Batch.
        /// </summary>
        public static string ValidCourseBatch {
            get {
                return ResourceManager.GetString("ValidCourseBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide valid VC request.
        /// </summary>
        public static string ValidVCRequest {
            get {
                return ResourceManager.GetString("ValidVCRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to process the VC request.
        /// </summary>
        public static string VCnotProcessed {
            get {
                return ResourceManager.GetString("VCnotProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VC Request has been approved..
        /// </summary>
        public static string VCRequestApproved {
            get {
                return ResourceManager.GetString("VCRequestApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VC Request has been rejected..
        /// </summary>
        public static string VCRequestRejected {
            get {
                return ResourceManager.GetString("VCRequestRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify your Email\n Verification link has been sent to your email.
        /// </summary>
        public static string VerifyMail {
            get {
                return ResourceManager.GetString("VerifyMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Conference service URL is not configured..
        /// </summary>
        public static string VideoConferenceUrlNotConfigure {
            get {
                return ResourceManager.GetString("VideoConferenceUrlNotConfigure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload .amv, .mp4 video formats only..
        /// </summary>
        public static string VideoType {
            get {
                return ResourceManager.GetString("VideoType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only view the details after assigning a course..
        /// </summary>
        public static string ViewAfterCourseAssigned {
            get {
                return ResourceManager.GetString("ViewAfterCourseAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webinar currently unavailable..
        /// </summary>
        public static string WebinarUnavailable {
            get {
                return ResourceManager.GetString("WebinarUnavailable", resourceCulture);
            }
        }
    }
}
