//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsHub.API.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SMSTemplate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SMSTemplate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SportsHub.API.Resources.SMSTemplate", typeof(SMSTemplate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert from {0}, {1} was absent today for the batch that starts at {2}. Regards, {3}. Thanks. SAMVAA.
        /// </summary>
        public static string absentAlert {
            get {
                return ResourceManager.GetString("absentAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0}, Welcome to {1}, Your admission has been confirmed. Regards, {2}. Thanks.SAMVAA..
        /// </summary>
        public static string admissionConformWelcome {
            get {
                return ResourceManager.GetString("admissionConformWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Parent, Classes are cancelled today due to {0} from {1} to {2} Student&apos;s Online Exam. Thanks. SAMVAA.
        /// </summary>
        public static string cancelledClass {
            get {
                return ResourceManager.GetString("cancelledClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0}, Your fee amount of {1} has been received on {2}. Total fee amount of Rs. {3}, Total received amount of Rs. {4}, Total pending amount of Rs. {5}. Thanks. SAMVAA.
        /// </summary>
        public static string feeAmountReceived {
            get {
                return ResourceManager.GetString("feeAmountReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0}, Your fee payment is due. This is a friendly reminder to submit it and ignore it if you already process it. The total pending amount is Rs. {1} and the due Installment amount is Rs. {2}.
        ///Regards, {3}. Thanks. SAMVAA..
        /// </summary>
        public static string feePaymentDue {
            get {
                return ResourceManager.GetString("feePaymentDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0}, Your login details for Samvaad LMS is: User Id: {1}, Password: {2}, Download the app from (Play store link Samvaad)¸URL: {3}{4}, Regards, {5}. Thanks.
        /// </summary>
        public static string loginDetails {
            get {
                return ResourceManager.GetString("loginDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0}, New online exam has been assigned to you for {1} and need to attend between {2} to {3}. Regards, {4}. Thanks. SAMVAA.
        /// </summary>
        public static string onlineExamAssign {
            get {
                return ResourceManager.GetString("onlineExamAssign", resourceCulture);
            }
        }
    }
}
